import "./globals.css";
import Navbar from "@/components/navbar";
import Banner from "@/components/banner";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>
      <Banner />
      <Navbar/>
      {children}
      </body>
    </html>
  );
}
